# Generated by Django 4.0.4 on 2022-11-10 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('coupe', 'Coupe'), ('sport', 'Sport'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('crossover', 'Crossover')], max_length=100, null=True)),
                ('brand', models.CharField(blank=True, choices=[('bmw', 'BMW'), ('audi', 'Audi'), ('mitsubishi', 'MITSUBISHI'), ('porsche', 'PORSCHE'), ('volkswagen', 'VOLKSWAGEN'), ('kia', 'KIA'), ('hyundai', 'Hyundai'), ('toyota', 'Toyota'), ('ferarri', 'Ferarri'), ('tesla', 'Tesla'), ('lada', 'Lada'), ('jac', 'JAC')], max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('countries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.country')),
            ],
        ),
    ]
