# Generated by Django 4.0.4 on 2022-05-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
