# Generated by Django 4.0.4 on 2022-11-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0005_book_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('coupe', 'Coupe'), ('sport', 'Sport'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('crossover', 'Crossover')], max_length=100, null=True)),
                ('brand', models.CharField(blank=True, choices=[('bmw', 'BMW'), ('audi', 'Audi'), ('mitsubishi', 'MITSUBISHI'), ('porsche', 'PORSCHE'), ('volkswagen', 'VOLKSWAGEN'), ('kia', 'KIA'), ('hyundai', 'Hyundai'), ('toyota', 'Toyota')], max_length=100, null=True)),
                ('price', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Fandom',
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.country'),
        ),
    ]
