# Generated by Django 4.0.4 on 2022-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_country_delete_book_delete_fandom_car_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, choices=[('germany', 'Germany'), ('japan', 'Japan'), ('korean', 'South Korean'), ('usa', 'USA'), ('china', 'China'), ('sweden', 'Sweden')], max_length=100, null=True),
        ),
    ]
