# Generated by Django 4.0.4 on 2022-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(blank=True, choices=[('germany', 'Germany'), ('japan', 'Japan'), ('korea', 'Korea'), ('usa', 'USA'), ('sweden', 'Sweden'), ('italy', 'Italy'), ('france', 'France'), ('england', 'England')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
