# Generated by Django 4.0.4 on 2022-11-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_rename_country_car_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, choices=[('bmw', 'BMW'), ('audi', 'Audi'), ('mitsubishi', 'MITSUBISHI'), ('porsche', 'PORSCHE'), ('volkswagen', 'VOLKSWAGEN'), ('kia', 'KIA'), ('hyundai', 'Hyundai'), ('toyota', 'Toyota'), ('ferarri', 'Ferarri'), ('tesla', 'Tesla')], max_length=100, null=True),
        ),
    ]
